[build]
  functions = "netlify/functions"
  publish = "build"
  command = "npm run build"

[[headers]]
for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"
  Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200